name: Build & Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:    
      - '*'

env:
  ORG_GRADLE_PROJECT_NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  ORG_GRADLE_PROJECT_SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

jobs:

  build-on-macos:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
    
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build sqllin-driver
        run: ./gradlew :sqllin-driver:assemble
        
      - name: Run sqllin-driver macOS X64 Tests
        run: ./test_driver_macos.sh

      - name: Build sqllin-dsl
        run: ./gradlew :sqllin-dsl:assemble

      - name: Run sqllin-dsl macOS X64 Tests
        run: ./test_dsl_macos.sh

      - name: Run Android 13 Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          profile: pixel_6
          script: ./test_android.sh

      - name: Upload sqllin-driver Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: sqllin-driver/build/reports
        if: always()

      - name: Upload sqllin-dsl Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: sqllin-dsl/build/reports
        if: always()

  build-on-windows:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build sqllin-driver
        run: ./gradlew :sqllin-driver:mingwX64MainKlibrary

      - name: Run sqllin-driver MinGW X64 Tests
        run: ./gradlew :sqllin-driver:cleanMingwX64Test && ./gradlew :sqllin-driver:mingwX64Test --stacktrace

      - name: Build sqllin-dsl
        run: ./gradlew :sqllin-dsl:mingwX64MainKlibrary

      - name: Run sqllin-dsl MinGW X64 Tests
        run: ./gradlew :sqllin-dsl:cleanMingwX64Test && ./gradlew :sqllin-dsl:mingwX64Test --stacktrace

      - name: Upload sqllin-driver Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: sqllin-driver/build/reports
        if: always()

      - name: Upload sqllin-dsl Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: sqllin-dsl/build/reports
        if: always()

  build-on-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build sqllin-driver
        run: ./gradlew :sqllin-driver:assemble

      - name: Run sqllin-driver Linux X64 Tests
        run: ./gradlew :sqllin-driver:cleanLinuxX64Test && ./gradlew :sqllin-driver:linuxX64Test --stacktrace

      - name: Build sqllin-processor
        run: ./gradlew :sqllin-processor:assemble

      - name: Build sqllin-dsl
        run: ./gradlew :sqllin-dsl:assemble

      - name: Run sqllin-dsl Linux X64 Tests
        run: ./gradlew :sqllin-dsl:cleanLinuxX64Test && ./gradlew :sqllin-dsl:linuxX64Test --stacktrace

      - name: Run Android 8 Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          target: default
          arch: x86_64
          profile: pixel_2
          script: ./test_android.sh

      - name: Upload sqllin-driver Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: sqllin-driver/build/reports
        if: always()

      - name: Upload sqllin-dsl Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: sqllin-dsl/build/reports
        if: always()
